name: Cowabunga

author: Joe Dean

main: org.tvcd.cowabunga.Cowabunga

commands:
    cowabunga:
        description: spawn 10 cows
    cowabunga_admin:
        description: spawn 10 cows

version: 0.1

